import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body
        className={` bg-zinc-900 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className='flex  justify-center p-12'>
          <button className="btn btn-primary">Finastar</button>
        </div>
        {children}
      </body>
    </html>
  );
}
