"""add regularity and last_payment_date to debts

Revision ID: 2ca4f138df54
Revises: 35d6c83065d8
Create Date: 2026-03-27 02:53:37.840773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca4f138df54'
down_revision: Union[str, Sequence[str], None] = '35d6c83065d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debts', sa.Column('regularity', sa.String(), nullable=True))
    op.add_column('debts', sa.Column('last_payment_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debts', 'last_payment_date')
    op.drop_column('debts', 'regularity')
    # ### end Alembic commands ###
