"""add crypto history

Revision ID: ff70b3ed954c
Revises: afb475d6fbb0
Create Date: 2026-04-28 03:58:19.134896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff70b3ed954c'
down_revision: Union[str, Sequence[str], None] = 'afb475d6fbb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('crypto_name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('consulted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto_history')
    # ### end Alembic commands ###
